name: halla
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  # UI and Animations
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  lottie: ^3.1.2
  animations: ^2.0.11
  shimmer:
  page_transition: ^2.1.0
  awesome_snackbar_content: ^0.1.3
  animated_search_bar: ^2.8.0

  # Forms and Input Handling
  pinput: ^5.0.0
  dropdown_search: ^6.0.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  flutter_contacts: any
  drag_and_drop_lists: ^0.4.1
  image_picker: ^1.1.2
  image_cropper: ^9.0.0

  # Firebase & Cloud Services
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_dynamic_links:
  firebase_messaging:
  # State Management & Dependency Injection
  flutter_bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  get_it: ^8.0.0

  # Storage & Caching
  path_provider: ^2.1.3
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.4.1
  isar_flutter_libs: ^4.0.0-dev.3
  cached_network_image:

  # Localization & Internationalization
  intl: ^0.19.0
  flutter_intl: ^0.0.1
  flutter_localizations:
    sdk: flutter
  arb_translate: ^1.1.0
  string_similarity: ^2.1.1
  fuzzywuzzy: ^1.2.0

  # Authentication & Security
  smart_auth:
  google_sign_in:
  nfc_manager: ^3.5.0
  encrypt: ^5.0.3
  uuid: ^4.4.2

  # Network & API Handling
  http:
  googleapis:
  googleapis_auth:
  fpdart: ^1.1.0
  internet_connection_checker: ^3.0.1

  # Geolocation & Maps
  geolocator: ^13.0.2
  latlong2:
  flutter_map:


  # Background Services & Notifications
  flutter_local_notifications:
  app_settings: ^5.1.1

  # Code Generation & Serialization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  meta: ^1.12.0

  # UI Navigation
  bottom_navy_bar: ^6.1.0
  pull_to_refresh_flutter3: ^2.0.2


  # AI & Generative Models
  google_generative_ai: ^0.4.6


  # handle permission
  permission_handler: ^11.4.0









dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  freezed: ^3.0.0-0.0.dev


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - assets/fonts/
  fonts:
    - family: IBM
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
