// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVyJpyYkDvVQ0yW-jp9PVXr0WCyuRYXgY',
    appId: '1:58856844270:android:3e41bec128bd2526a43cff',
    messagingSenderId: '58856844270',
    projectId: 'halla-ca',
    storageBucket: 'halla-ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDymHzEjFuDAVKk7PqbACn7EuOzmT_D-To',
    appId: '1:58856844270:ios:80ab8b43db6b1eafa43cff',
    messagingSenderId: '58856844270',
    projectId: 'halla-ca',
    storageBucket: 'halla-ca.appspot.com',
    androidClientId: '58856844270-b5gbi7nmhrpcao7hhfnced718n5ebvcb.apps.googleusercontent.com',
    iosClientId: '58856844270-3sv4im9uicuvi86op1fcvrabbcc3vl0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.hallaCa',
  );

}